[WIP] 3. PaymentRequest interface
kosen14s/Yurufuwa-PaymentRequestAPI pull request #7
Opened 2017-03-13 14:25 UTC by yamasy1549

issue: #4 

# TODO
- [x] [3. PaymentRequest interface](https://www.w3.org/TR/payment-request/#paymentrequest-interface) intro
- [ ] [3.1. Constructor](https://www.w3.org/TR/payment-request/#constructor)

2017-03-13 14:26 UTC, yamasy1549 commented on 3_PaymentRequest_interface.md
> +これは一般的に決済処理を始めるユーザーに関連付けられます（例えばゲームで「パワーアップ」を選択したり、立体駐車場を利用して精算機に向かったり、「買う」「支払う」といったボタンを押したりする）。
@theoldmoon0602 このへん特に不自然なのでぴったりな日本語がほしい 🍢

2017-03-20 08:32 UTC, theoremoon requested changes

2017-03-20 08:32 UTC, theoremoon commented on 3_PaymentRequest_interface.md
> +これは一般的に決済処理を始めるユーザーに関連付けられます（例えばゲームで「パワーアップ」を選択したり、立体駐車場を利用して精算機に向かったり、「買う」「支払う」といったボタンを押したりする）。
「立体駐車場で、（車を）精算機に着ける」でどうですか

2017-03-20 08:32 UTC, theoldmoon0602 commented on 3_PaymentRequest_interface.md
> +details オブジェクトには例えば注文の詳細など、ユーザーの確認が求められている取引についての情報が含まれています。
ask A to complete は 「Aに記入させる」「Aに提出させる」っぽいので
「ユーザの入力が求められている取引についての情報が」にしたい感じがある？

2017-03-20 09:29 UTC, theoremoon approved these changes
lgtm!

2017-03-20 09:40 UTC, yamasy1549 commented
やったぜ（まだある）

2017-03-20 10:28 UTC, yamasy1549 commented
@theoldmoon0602 みて

2017-03-20 12:57 UTC, theoremoon requested changes
ところどころ僕の見てる文書と差異があるんだけど、どれみてますか（僕はこれ https://www.w3.org/TR/payment-request

2017-03-20 12:57 UTC, theoldmoon0602 commented on 3_PaymentRequest_interface.md
> +  2. shippingOptions が存在するとき
details.shippingOptions が～くらいが適当っぽい

2017-03-20 12:57 UTC, theoldmoon0602 commented on 3_PaymentRequest_interface.md
> +     3. option.id を seenIds に追加します。
typo: seenIDs

2017-03-20 12:57 UTC, theoldmoon0602 commented on 3_PaymentRequest_interface.md
> +    2. options を details.shippingOptions とします。
これ、文章の便宜上名前を変えただけっぽく読んじゃったので、 「datails.shippingOptionsを（新しい変数）optionsにコピーします」くらいでいいかも

2017-03-20 12:57 UTC, theoldmoon0602 commented on 3_PaymentRequest_interface.md
> +10. serializedMethodData を空のリストにします。
typo: serializedModifierData

2017-03-20 12:57 UTC, theoldmoon0602 commented on 3_PaymentRequest_interface.md
> +  2. modifiers が存在するとき
これも details.modifiers とかでよさそう

2017-03-20 12:57 UTC, theoldmoon0602 commented on 3_PaymentRequest_interface.md
> +1. paymentRequestId が与えられていなければ、 paymentRequestId が作られます。
おっ、こんなのあったっけか

2017-03-20 12:57 UTC, theoldmoon0602 commented on 3_PaymentRequest_interface.md
> +  この振る舞いにより、ページはサポートされていない配送方法を提供したかどうかを検出できます。将来の仕様で新しい配送方法が追加されても以前のバージョンをサポートしているユーザーエージェントでページを実行している場合に、これは重要となります。
おっ、こんなのあったっけか

2017-03-20 13:04 UTC, yamasy1549 commented on 3_PaymentRequest_interface.md
> +1. paymentRequestId が与えられていなければ、 paymentRequestId が作られます。
おもしろい。ぼくもそれどこを見たのかわからない。

2017-03-20 13:05 UTC, yamasy1549 commented on 3_PaymentRequest_interface.md
> +  この振る舞いにより、ページはサポートされていない配送方法を提供したかどうかを検出できます。将来の仕様で新しい配送方法が追加されても以前のバージョンをサポートしているユーザーエージェントでページを実行している場合に、これは重要となります。
なんか後の章のと混じってる気がしてきた。ゆるちて

2017-03-20 13:05 UTC, yamasy1549 commented
ぼくgdgdやんけ！

2017-03-20 13:07 UTC, theoldmoon0602 commented
そのための review なんだよなぁ（というか翻訳してない僕はgdgdにもなれない

2017-03-20 13:07 UTC, yamasy1549 commented
おうどんどん翻訳しろよ

2017-03-20 13:17 UTC, yamasy1549 commented
@theoldmoon0602 なおちた

2017-03-22 00:42 UTC, theoremoon approved these changes
ok tarou

2017-03-22 14:07 UTC, merged